### ISSUE TITLE
Plugin not connected to android phone

### ISSUE THREAD

**Issue by AravindhJey** [randdusing/ng-cordova-bluetoothle#26]
Hi all, I am using this plugin for connecting embedded device. before that I want to check it with 2 mobiles. But it is not even finding my mobile device..

**Comment by randdusing** [comment]
Please post issue on plugin repo since it's most likely not an issue with ng-cordova-bluetoothle. Are you on Android or iOS? If on Android, make sure you request the proper permissions. And make sure the other mobile devices are actually advertising BLE. Most likely they aren't unless you downloaded or wrote an app for them to do so.
